### ISSUE TITLE
Refinement of search interface

### ISSUE THREAD

**Issue by OmarHussainX** [OmarHussainX/HUDDLE#5]
![Screenshot from 2019-03-26 11-10-47](https://user-images.githubusercontent.com/44478074/55018184-e4569600-4fb7-11e9-9f2c-5fdd1dc5ea3b.png)
Got the checkbox controls compressed nicely, as shown in the screen capture, but... I think the search UI needs to be cleaned/refined. It may even be advisable IMHO, to remove the ability to filter by day entirely - at least from this view, and/or until we can think of a cleaner way to expose this feature

I think it's confusing - from a user's perspective - to be able to pick a date, _and_ then also have the ability to select day(s) which have no connection to their desired date.

The problem with removing the day-of-week checkboxes and keeping the date, start, end time fields is that the former have search logic, the latter do not :confused: (edited).

Added user testing/feedback to first milestone (thought dump doc in our shared folder) - fair chance that outsiders will discover issues with the UI/flow/functionality that we can't see because we're too close to the project.

**Comment by OmarHussainX** [comment]
![Screenshot from 2019-03-26 12-12-22](https://user-images.githubusercontent.com/44478074/55022915-4bc51380-4fc1-11e9-9148-70be1c2b6c50.png)
In the same vein, not sure how best to handle quadrant search.

Original vision was: Street address search field, quadrant dropdown, city search field - all in one row

However, there's no way to fit all three in one row on mobile. What I've done now is to hide the quadrant search unless the city is Edmonton, or Calgary (which leads to another issue: how many cities have quadrant? Not a huge deal, could just have an array of cities with quadrants, but still...)

**Proposal**: Drop quadrant based search. Seriously - it only matters for a few cities, and we should design for the norm, not the exception.

Another option is to include quadrant data with street data. Then quadrant based searches can simply be handled through the street address search input field. It wouldn't be ideal - there'd be fair number of questionable (but correct) positives e.g. a search of street addresses for 'NE', would match '12 Landsdowne Rd. _SW_'.

**Comment by mrjoedang** [comment]
Resolved.

- Hide additional settings in the 'Advanced search' section
- Probably drop quadrant but we'll use user feedback to guide us.
- Priority should be to have search functionality working for Rate and/or Capacity for now and then include more search features later.
